### ISSUE TITLE
增加掉落识别数据集

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaTestSet#1]
来张没有剿灭卡打的剿灭（ from https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2422 ）
![](https://user-images.githubusercontent.com/116583630/197579742-ae41f3c9-5892-4560-a80e-d0b4705b9ab2.png)

**Comment by zzyyyl** [comment]
以及 OF-F4 （ from https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2360#issuecomment-1288996460 ）
![](https://user-images.githubusercontent.com/74587068/197530944-903d1e81-7656-439f-88d5-59b2c1ab708b.png)

**Comment by MistEO** [comment]
你自己放进去啊喂（
